### ISSUE TITLE
yo bitrix:component - Error: Cannot find module '../lib/util'

### ISSUE THREAD

**Issue by Scarboroid** [stee1cat/generator-bitrix#1]
```
> yo bitrix:component
module.js:545
    throw err;
    ^

Error: Cannot find module '../lib/util'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Tardis\AppData\Roaming\npm\node_modules\generator-bitrix\component\index.js:10:12)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```
Что я делаю не так?

**Comment by stee1cat** [comment]
Thanks! Fixed.
